name: Conty AutoRelease CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          lfs: 'false'

      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v6
        with:
          workflow: utils.yml
          workflow_conclusion: success
          if_no_artifact_found: ignore
          path: /opt

      - name: Build Conty
        run: |
          if [ -f /opt/Utils/utils.tar.gz ]; then
              cp /opt/Utils/* .
          fi

          chmod +x create-arch-bootstrap.sh create-conty.sh
          sudo ./create-arch-bootstrap.sh && ./create-conty.sh

          if [ "$(stat -c%s conty.sh)" -gt 2097152000 ]; then
            split -b 2097152000 --numeric-suffixes=1 conty.sh conty.sh_part
            rm conty.sh
          fi

      - name: Delete tag and release
        run: |
          if gh release view continuous; then
            gh release delete continuous -y
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: rickstaa/action-create-tag@v1
        id: "tag_create"
        with:
          tag: "continuous"

      - uses: softprops/action-gh-release@v1
        with:
          files: ./conty.sh*
          prerelease: true
          draft: false
          tag_name: continuous
          name: Continuous build
