name: Conty AutoRelease CI

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: 'false'

      - name: Download artifact
        uses: dawidd6/action-download-artifact@v6
        with:
          workflow: utils.yml
          workflow_conclusion: success
          if_no_artifact_found: ignore
          path: /opt

      - name: Build Conty
        run: |
          if [ -f /opt/Utils/utils.tar.gz ]; then
              cp /opt/Utils/* .
          fi

          chmod +x create-arch-bootstrap.sh create-conty.sh
          sudo ./create-arch-bootstrap.sh && ./create-conty.sh

          if [ "$(stat -c%s conty.sh)" -gt 2097152000 ]; then
            split -b 2097152000 --numeric-suffixes=1 conty.sh conty.sh_part
            rm conty.sh
          fi

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          name: ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
          files: ./conty.sh*
          make_latest: true
