name: Conty AutoRelease CI

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: 'false'

      - name: Download artifact
        uses: dawidd6/action-download-artifact@v6
        with:
          workflow: utils.yml
          workflow_conclusion: success
          if_no_artifact_found: ignore
          path: /opt

      - name: Build Conty
        run: |
          if [ -f /opt/Utils/utils.tar.gz ]; then
              cp /opt/Utils/* .
          fi

          chmod +x create-arch-bootstrap.sh create-conty.sh
          sudo ./create-arch-bootstrap.sh && ./create-conty.sh

          if [ "$(stat -c%s conty.sh)" -gt 2097152000 ]; then
            split -b 2097152000 --numeric-suffixes=1 conty.sh conty.sh_part
            rm conty.sh
          fi

      - name: Delete tag and release
        run: |
          if gh release view auto; then
            gh release delete auto --cleanup-tag -yes
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Tag commit
        uses: rickstaa/action-create-tag@v1
        with:
          tag: "auto"

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: Auto Release
          tag_name: auto 
          files: ./conty.sh*
          prerelease: true
          draft: false
